### PR TITLE
Add a new NavBar

### PR DESCRIPTION
**Pull request by chamindujs**
I designed a new navbar for the website as been told as in #6 . 

In my opinion, a drop-down menu is not a good UI choice. So I didn't include one

### The new look =
image

### CODE REVIEW

**Comment by Misly16** [comment]
As this is a css framework could you make one that doesn't rely on bootstrap

**Comment by chamindujs** [comment]
On it!

**Comment by chamindujs** [comment]
Done!

**Comment by Misly16** [comment]
Thanks ill push this later today and i'll add some more features

**Comment by chamindujs** [comment]
Thanks,
Can you merge this PR, please? So it would count towards Hacktoberfest.

**Comment by chamindujs** [comment]
@Misly16   Hey, can you add **"hacktoberfest-accepted"** label to my PR? So my contribution would count towards because there was some change of rules. 

image

Please be kind enough to consider my message.

**Comment by Misly16** [comment]
done!

**Pull request merged**
